name: repo_viewer
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^5.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  webview_flutter: ^3.0.2
  flash: ^2.0.3+2
  auto_route: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  freezed: ^1.1.1
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true
